version: "3.9"

volumes:
  postgres_volume:

services:
  travel_crm:
    build:
      context: .
    container_name: app
    restart: always
    ports:
      - "8050:8545"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/travel_crm_database"
      SPRING_DATASOURCE_USERNAME: "travel_crm_admin"
      SPRING_DATASOURCE_PASSWORD: "travel_crm_admin"
    networks:
      - postgres

  postgres:
    image: postgres:13.3
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: "travel_crm_admin"
      POSTGRES_PASSWORD: "travel_crm_admin"
      POSTGRES_DB: "travel_crm_database"
    ports:
      - "5432:5432"
    networks:
      - postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data

networks:
  postgres:
    driver: bridge