version: "3.9"

volumes:
  postgres_volume:

services:
  travel_crm:
    image: 7hiago/travel-crm-app-image
    container_name: travel-crm-app-container
    restart: always
    ports:
      - "8050:8050"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-db-container:5432/travel_crm_database"
      SPRING_DATASOURCE_USERNAME: "travel_crm_admin"
      SPRING_DATASOURCE_PASSWORD: "travel_crm_admin"
      API_URL: "http://course-aggregator-app-container:8060/api/bestCourse"
    networks:
      - db-network
      - app-network

  postgres:
    image: postgres:13.3
    container_name: postgres-db-container
    restart: always
    environment:
      POSTGRES_USER: "travel_crm_admin"
      POSTGRES_PASSWORD: "travel_crm_admin"
      POSTGRES_DB: "travel_crm_database"
    ports:
      - "5432:5432"
    networks:
      - db-network
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  course-aggregator:
    image: 7hiago/course-aggregator-app-image
    container_name: course-aggregator-app-container
    restart: always
    ports:
      - "8060:8060"
    networks:
      - app-network

networks:
  db-network:
    driver: bridge
  app-network:
    driver: bridge